package codegen;

import javax.swing.table.AbstractTableModel;

/**
 * @author Deckard He
 */
public class impMainScene extends javax.swing.JFrame {

    protected String[] options;
    protected AbstractTableModel resultTableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton ButtonCleanCidInput;
    protected javax.swing.JButton ButtonDeleteData;
    protected javax.swing.JButton ButtonExportData;
    protected javax.swing.JButton ButtonSearch;
    protected javax.swing.JLabel LabelDoing;
    protected javax.swing.JLabel LabelStatusValue;
    protected javax.swing.JMenu MenuFile;
    protected javax.swing.JMenu MenuHelp;
    protected javax.swing.JMenuItem MenuItemAbout;
    protected javax.swing.JMenuItem MenuItemAddSuffix;
    //</Auto-Generate>
    protected javax.swing.JMenuItem MenuItemConn;
    protected javax.swing.JMenuItem MenuItemExit;
    protected javax.swing.JProgressBar ProgressBarDoing;
    protected javax.swing.JTable TableMain;
    protected javax.swing.JTextField TextFieldCidInput;
    private javax.swing.JComboBox<String> ComboBoxModules;
    private javax.swing.JLabel LabelCid;
    private javax.swing.JLabel LabelModules;
    private javax.swing.JLabel LabelStatus;
    private javax.swing.JMenuBar MenuBarMain;
    private javax.swing.JPanel PanelTable;
    private javax.swing.JPanel PanelTextFieldWrapper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;

    /**
     * Creates new form MainScene
     */
    public impMainScene() {
        this.options = new String[]{"op1", "op2", "op3"};
        this.resultTableModel = new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {"EMPTY", "EMPTY", "EMPTY"},
                },
                new String[]{
                        "Cid", "Channel count", "Date"
                }
        );
        initComponents();
        this.middle();
    }

    public impMainScene(String[] options, AbstractTableModel model) {
        this.options = options;
        this.resultTableModel = model;
        initComponents();
        this.middle();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new impMainScene().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelCid = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabelStatus = new javax.swing.JLabel();
        LabelStatusValue = new javax.swing.JLabel();
        ProgressBarDoing = new javax.swing.JProgressBar();
        LabelDoing = new javax.swing.JLabel();
        LabelModules = new javax.swing.JLabel();
        ComboBoxModules = new javax.swing.JComboBox<>();
        PanelTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableMain = new javax.swing.JTable();
        ButtonExportData = new javax.swing.JButton();
        PanelTextFieldWrapper = new javax.swing.JPanel();
        TextFieldCidInput = new javax.swing.JTextField();
        ButtonCleanCidInput = new javax.swing.JButton();
        ButtonDeleteData = new javax.swing.JButton();
        ButtonSearch = new javax.swing.JButton();
        MenuBarMain = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuItemConn = new javax.swing.JMenuItem();
        MenuItemAddSuffix = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuItemExit = new javax.swing.JMenuItem();
        MenuHelp = new javax.swing.JMenu();
        MenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icon/16px/db.png")).getImage());

        LabelCid.setText("Taodata level 4 cid: ");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        LabelStatus.setText("Database Status: ");

        LabelStatusValue.setForeground(new java.awt.Color(255, 0, 51));
        LabelStatusValue.setText("Disconnected");

        LabelDoing.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LabelStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelStatusValue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelDoing, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ProgressBarDoing, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(LabelStatus)
                                                .addComponent(LabelStatusValue)
                                                .addComponent(LabelDoing))
                                        .addComponent(ProgressBarDoing, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(7, Short.MAX_VALUE))
        );

        LabelModules.setText("Search on module: ");

        ComboBoxModules.setModel(new javax.swing.DefaultComboBoxModel<>(this.options));
        ComboBoxModules.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxModulesItemStateChanged(evt);
            }
        });

        TableMain.setModel(this.resultTableModel);
        TableMain.setRowSelectionAllowed(false);
        TableMain.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TableMain.setShowHorizontalLines(true);
        TableMain.setShowVerticalLines(true);
        jScrollPane2.setViewportView(TableMain);

        javax.swing.GroupLayout PanelTableLayout = new javax.swing.GroupLayout(PanelTable);
        PanelTable.setLayout(PanelTableLayout);
        PanelTableLayout.setHorizontalGroup(
                PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2)
        );
        PanelTableLayout.setVerticalGroup(
                PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );

        ButtonExportData.setText("Export Selected Data");
        ButtonExportData.setToolTipText("By default if you don't select any row it will exports all data");
        ButtonExportData.setFocusable(false);
        ButtonExportData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExportDataActionPerformed(evt);
            }
        });

        PanelTextFieldWrapper.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TextFieldCidInput.setBorder(null);

        ButtonCleanCidInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16px/clear.png"))); // NOI18N
        ButtonCleanCidInput.setBorder(null);
        ButtonCleanCidInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCleanCidInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTextFieldWrapperLayout = new javax.swing.GroupLayout(PanelTextFieldWrapper);
        PanelTextFieldWrapper.setLayout(PanelTextFieldWrapperLayout);
        PanelTextFieldWrapperLayout.setHorizontalGroup(
                PanelTextFieldWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelTextFieldWrapperLayout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(TextFieldCidInput, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ButtonCleanCidInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelTextFieldWrapperLayout.setVerticalGroup(
                PanelTextFieldWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelTextFieldWrapperLayout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(PanelTextFieldWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextFieldCidInput)
                                        .addComponent(ButtonCleanCidInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        ButtonDeleteData.setText("Delete Selected Data");
        ButtonDeleteData.setFocusable(false);
        ButtonDeleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteDataActionPerformed(evt);
            }
        });

        ButtonSearch.setText("Search Now");
        ButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSearchActionPerformed(evt);
            }
        });

        MenuFile.setText("File");

        MenuItemConn.setText("Connect to DB");
        MenuItemConn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemConnActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemConn);

        MenuItemAddSuffix.setText("Set Query Suffix");
        MenuItemAddSuffix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAddSuffixActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemAddSuffix);
        MenuFile.add(jSeparator1);

        MenuItemExit.setText("Exit");
        MenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemExitActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemExit);

        MenuBarMain.add(MenuFile);

        MenuHelp.setText("Help");

        MenuItemAbout.setText("About");
        MenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAboutActionPerformed(evt);
            }
        });
        MenuHelp.add(MenuItemAbout);

        MenuBarMain.add(MenuHelp);

        setJMenuBar(MenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(LabelModules)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ComboBoxModules, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(ButtonSearch)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                                                .addComponent(ButtonDeleteData)
                                                .addGap(18, 18, 18)
                                                .addComponent(ButtonExportData))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(LabelCid)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(PanelTextFieldWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addComponent(PanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(LabelCid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PanelTextFieldWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ComboBoxModules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LabelModules)
                                        .addComponent(ButtonExportData)
                                        .addComponent(ButtonDeleteData)
                                        .addComponent(ButtonSearch))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemExitActionPerformed
        impMenuItemExitActionPerformed(evt);
    }//GEN-LAST:event_MenuItemExitActionPerformed

    private void MenuItemConnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemConnActionPerformed
        impMenuItemConnActionPerformed(evt);
    }//GEN-LAST:event_MenuItemConnActionPerformed

    private void MenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAboutActionPerformed
        impMenuItemAboutActionPerformed(evt);
    }//GEN-LAST:event_MenuItemAboutActionPerformed

    private void ComboBoxModulesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxModulesItemStateChanged
        impComboBoxModulesItemStateChanged(evt);
    }//GEN-LAST:event_ComboBoxModulesItemStateChanged

    private void ButtonExportDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExportDataActionPerformed
        impButtonExportDataActionPerformed(evt);
    }//GEN-LAST:event_ButtonExportDataActionPerformed

    private void ButtonCleanCidInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCleanCidInputActionPerformed
        impButtonCleanCidInputActionPerformed(evt);
    }//GEN-LAST:event_ButtonCleanCidInputActionPerformed

    private void ButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchActionPerformed
        impButtonSearchActionPerformed(evt);
    }//GEN-LAST:event_ButtonSearchActionPerformed

    private void ButtonDeleteDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteDataActionPerformed
        impButtonDeleteDataActionPerformed(evt);
    }//GEN-LAST:event_ButtonDeleteDataActionPerformed

    private void MenuItemAddSuffixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAddSuffixActionPerformed
        impMenuItemAddSuffixActionPerformed(evt);
    }//GEN-LAST:event_MenuItemAddSuffixActionPerformed

    protected final void middle() {
        this.setLocationRelativeTo(null);
    }
    // End of variables declaration//GEN-END:variables

    //<Auto-Generate-Result>
    protected void impMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {
    }

    protected void impMenuItemConnActionPerformed(java.awt.event.ActionEvent evt) {
    }

    protected void impMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {
    }

    protected void impComboBoxModulesItemStateChanged(java.awt.event.ItemEvent evt) {
    }

    protected void impButtonExportDataActionPerformed(java.awt.event.ActionEvent evt) {
    }

    protected void impButtonCleanCidInputActionPerformed(java.awt.event.ActionEvent evt) {
    }

    protected void impButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {
    }

    protected void impButtonDeleteDataActionPerformed(java.awt.event.ActionEvent evt) {
    }

    protected void impMenuItemAddSuffixActionPerformed(java.awt.event.ActionEvent evt) {
    }
    //</Auto-Generate-Result>
}
